import { IChat } from '../types/chat';
import { IGame, IGameEvent } from '../types/game';
import { IGroup, IGroupPost } from '../types/group';
import { IMarketplaceListing } from '../types/marketplace';
import { IPost } from '../types/post';
import { IReel } from '../types/reel';
import { IStory } from '../types/user';

export const postsData: IPost[] = [
  {
    _id: '1',
    user: {
      _id: '1',
      username: 'jake_mitchell',
      fullName: 'Jake Mitchell',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'Captured this moment during the golden hour last evening. The sky was absolutely breathtaking — shades of amber, rose, and violet bleeding into each other. Sometimes you just have to put the phone down and soak it all in. Grateful for these little reminders that the world is still beautiful. 🌅',
    image: 'https://random.imagecdn.app/1920/1081',
    likes: 129,
    comments: 5,
    commentsData: [
      {
        _id: 'c1',
        user: {
          _id: 'u2',
          fullName: 'Andrew Roberts',
          dp: 'https://random.imagecdn.app/210/210',
        },
        text: 'Great shot! Love the composition here.',
        likes: 16,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 7 * 3600000),
        replies: [
          {
            _id: 'c1r1',
            user: {
              _id: 'u3',
              fullName: 'Ryan Cooper',
              dp: 'https://random.imagecdn.app/211/211',
            },
            text: 'Totally agree!',
            likes: 4,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 6 * 3600000),
          },
        ],
      },
      {
        _id: 'c2',
        user: {
          _id: 'u4',
          fullName: 'Emily Carter',
          dp: 'https://random.imagecdn.app/212/212',
        },
        text: 'Wow, this is absolutely stunning!',
        likes: 8,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
      {
        _id: 'c3',
        user: {
          _id: 'u5',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/213/213',
        },
        text: 'Where was this taken? The lighting is perfect.',
        likes: 12,
        reactions: ['fas fa-thum  bs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 4 * 3600000),
      },
      {
        _id: 'c4',
        user: {
          _id: 'u6',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/214/214',
        },
        text: 'This deserves way more likes!',
        likes: 3,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
      {
        _id: 'c5',
        user: {
          _id: 'u7',
          fullName: 'Jason Foster',
          dp: 'https://random.imagecdn.app/215/215',
        },
        text: 'Keep posting more content like this.',
        likes: 6,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 0,
    sharesData: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    user: {
      _id: '1',
      fullName: 'Jake Mitchell',
      username: 'jake_mitchell',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'Just wrapped up an incredible weekend retreat with the team. Three days of deep work, honest conversations, and a whole lot of laughter. It is amazing what can happen when you unplug from the noise and actually connect with the people around you. Already looking forward to the next one. Thank you all for making it unforgettable! 🙏✨',
    image: 'https://random.imagecdn.app/1920/1070',
    likes: 798,
    comments: 52,
    commentsData: [
      {
        _id: 'c6',
        user: {
          _id: 'u8',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/216/216',
        },
        text: 'This is absolutely fire! 🔥',
        likes: 45,
        reactions: ['fas fa-fire', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 10 * 3600000),
        replies: [
          {
            _id: 'c6r1',
            user: {
              _id: 'u9',
              fullName: 'Marcus Henderson',
              dp: 'https://random.imagecdn.app/217/217',
            },
            text: 'Completely agree with this!',
            likes: 9,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 9 * 3600000),
          },
          {
            _id: 'c6r2',
            user: {
              _id: 'u10',
              fullName: 'Henry Kane',
              dp: 'https://random.imagecdn.app/218/218',
            },
            text: 'Same! Sharing this right now.',
            likes: 5,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 8 * 3600000),
          },
        ],
      },
      {
        _id: 'c7',
        user: {
          _id: 'u11',
          fullName: 'Russell Hansen',
          dp: 'https://random.imagecdn.app/219/219',
        },
        text: 'Been waiting for this. So glad you posted it.',
        likes: 22,
        reactions: ['fas fa-thumbs-up', 'fas fa-surprise'],
        createdAt: new Date(Date.now() - 8 * 3600000),
      },
      {
        _id: 'c8',
        user: {
          _id: 'u12',
          fullName: 'Nathan Hayes',
          dp: 'https://random.imagecdn.app/220/220',
        },
        text: 'The quality is next level. 👌',
        likes: 31,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 6 * 3600000),
        replies: [
          {
            _id: 'c8r1',
            user: {
              _id: 'u13',
              fullName: 'Kevin Andrews',
              dp: 'https://random.imagecdn.app/221/221',
            },
            text: 'Could not have said it better!',
            likes: 7,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 5 * 3600000),
          },
        ],
      },
      {
        _id: 'c9',
        user: {
          _id: 'u14',
          fullName: 'Scott Irving',
          dp: 'https://random.imagecdn.app/222/222',
        },
        text: 'Sharing this with everyone I know.',
        likes: 14,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 4 * 3600000),
      },
      {
        _id: 'c10',
        user: {
          _id: 'u15',
          fullName: 'Travis Ingram',
          dp: 'https://random.imagecdn.app/223/223',
        },
        text: 'This made my day! Thanks for sharing.',
        likes: 19,
        reactions: ['fas fa-laugh', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
    ],
    shares: 10,
    sharesData: [
      {
        _id: 's1',
        user: {
          _id: 'u30',
          fullName: 'Ethan Bishop',
          dp: 'https://random.imagecdn.app/230/230',
        },
        sharedAt: new Date(Date.now() - 5 * 86400000),
      },
      {
        _id: 's2',
        user: {
          _id: 'u31',
          fullName: 'Ryan Hale',
          dp: 'https://random.imagecdn.app/231/231',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's3',
        user: {
          _id: 'u32',
          fullName: 'Aaron Hudson',
          dp: 'https://random.imagecdn.app/232/232',
        },
        caption: 'This is exactly what I needed to see today!',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    user: {
      _id: '1',
      fullName: 'Jake Mitchell',
      username: 'jake_mitchell',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption:
      'Started learning a new skill this month and honestly it has been humbling. There is something powerful about being a beginner again — the curiosity, the small wins, the inevitable frustration. Growth never stops if you keep showing up. Drop a 💪 if you are also working on something new right now!',
    image: 'https://random.imagecdn.app/1920/1060',
    likes: 456,
    comments: 15,
    commentsData: [
      {
        _id: 'c11',
        user: {
          _id: 'u16',
          fullName: 'Frank Harrison',
          dp: 'https://random.imagecdn.app/224/224',
        },
        text: 'This is the kind of content I follow you for.',
        likes: 28,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 11 * 3600000),
      },
      {
        _id: 'c12',
        user: {
          _id: 'u17',
          fullName: 'Rick Chapman',
          dp: 'https://random.imagecdn.app/225/225',
        },
        text: 'Absolutely stunning work. Keep it up!',
        likes: 11,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 9 * 3600000),
        replies: [
          {
            _id: 'c12r1',
            user: {
              _id: 'u18',
              fullName: 'Jack Harrison',
              dp: 'https://random.imagecdn.app/226/226',
            },
            text: 'Agreed 100%!',
            likes: 3,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 8 * 3600000),
          },
        ],
      },
      {
        _id: 'c13',
        user: {
          _id: 'u19',
          fullName: 'Sam Reynolds',
          dp: 'https://random.imagecdn.app/227/227',
        },
        text: 'Best one yet! Can not wait to see more.',
        likes: 17,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
    ],
    shares: 80,
    sharesData: [
      {
        _id: 's4',
        user: {
          _id: 'u33',
          fullName: 'Samuel Davis',
          dp: 'https://random.imagecdn.app/233/233',
        },
        sharedAt: new Date(Date.now() - 10 * 86400000),
      },
      {
        _id: 's5',
        user: {
          _id: 'u34',
          fullName: 'Zachary Hansen',
          dp: 'https://random.imagecdn.app/234/234',
        },
        caption: 'Everyone should see this. Sharing with my circle!',
        sharedAt: new Date(Date.now() - 7 * 86400000),
      },
      {
        _id: 's6',
        user: {
          _id: 'u35',
          fullName: 'Isaac Hudson',
          dp: 'https://random.imagecdn.app/235/235',
        },
        sharedAt: new Date(Date.now() - 4 * 86400000),
      },
      {
        _id: 's7',
        user: {
          _id: 'u36',
          fullName: 'Robert Irving',
          dp: 'https://random.imagecdn.app/236/236',
        },
        caption: 'Must watch!',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    user: {
      _id: '1',
      fullName: 'Jake Mitchell',
      username: 'jake_mitchell',
      dp: 'https://random.imagecdn.app/500/200',
    },
    caption: 'Coffee. Code. Repeat. ☕',
    image: 'https://random.imagecdn.app/1920/1050',
    likes: 29,
    comments: 1,
    commentsData: [
      {
        _id: 'c14',
        user: {
          _id: 'u20',
          fullName: 'Mark Udell',
          dp: 'https://random.imagecdn.app/228/228',
        },
        text: 'First comment! Great post as always.',
        likes: 2,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 2,
    sharesData: [
      {
        _id: 's8',
        user: {
          _id: 'u37',
          fullName: 'Kevin Udell',
          dp: 'https://random.imagecdn.app/237/237',
        },
        sharedAt: new Date(Date.now() - 3 * 86400000),
      },
      {
        _id: 's9',
        user: {
          _id: 'u38',
          fullName: 'Shane Kane',
          dp: 'https://random.imagecdn.app/238/238',
        },
        caption: 'Coffee culture is real ☕',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '5',
    user: {
      _id: 'u2',
      fullName: 'Emily Carter',
      username: 'emily_carter',
      dp: 'https://random.imagecdn.app/212/212',
    },
    caption:
      'Finally finished decorating my home office and I am absolutely in love with how it turned out! A cozy corner, good lighting, and plants everywhere — the perfect setup to do my best work. Your environment really does shape your mindset. 🌿💻',
    image: 'https://random.imagecdn.app/1920/1040',
    likes: 342,
    comments: 18,
    commentsData: [
      {
        _id: 'c15',
        user: {
          _id: 'u3',
          fullName: 'Ryan Cooper',
          dp: 'https://random.imagecdn.app/211/211',
        },
        text: 'This setup is goals! What plant is that on the shelf?',
        likes: 14,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 3 * 3600000),
        replies: [
          {
            _id: 'c15r1',
            user: {
              _id: 'u2',
              fullName: 'Emily Carter',
              dp: 'https://random.imagecdn.app/212/212',
            },
            text: "It's a pothos! Super easy to care for. 🌱",
            likes: 8,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 2 * 3600000),
          },
        ],
      },
      {
        _id: 'c16',
        user: {
          _id: 'u5',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/213/213',
        },
        text: 'The vibes in this photo are immaculate. Seriously inspiring!',
        likes: 9,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
    ],
    shares: 12,
    sharesData: [
      {
        _id: 's10',
        user: {
          _id: 'u39',
          fullName: 'Raymond Andrews',
          dp: 'https://random.imagecdn.app/239/239',
        },
        sharedAt: new Date(Date.now() - 6 * 86400000),
      },
      {
        _id: 's11',
        user: {
          _id: 'u40',
          fullName: 'Bradley Hudson',
          dp: 'https://random.imagecdn.app/240/240',
        },
        caption: 'Home office goals right here 🌿',
        sharedAt: new Date(Date.now() - 3 * 86400000),
      },
      {
        _id: 's12',
        user: {
          _id: 'u41',
          fullName: 'Brian Hudson',
          dp: 'https://random.imagecdn.app/241/241',
        },
        sharedAt: new Date(Date.now() - 12 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 1 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    user: {
      _id: 'u3',
      fullName: 'Ryan Cooper',
      username: 'ryan_dev',
      dp: 'https://random.imagecdn.app/211/211',
    },
    caption:
      'Shipped my first open-source project today 🚀 Months of late nights, endless refactors, and a mountain of Stack Overflow tabs — but it is finally live! If you are a developer, you know this feeling. Link in bio. Would love feedback from the community!',
    image: 'https://random.imagecdn.app/1920/1030',
    likes: 621,
    comments: 34,
    commentsData: [
      {
        _id: 'c17',
        user: {
          _id: 'u1',
          fullName: 'Jake Mitchell',
          dp: 'https://random.imagecdn.app/500/200',
        },
        text: 'Congrats man! This is huge. Going to check it out right now.',
        likes: 27,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 5 * 3600000),
      },
      {
        _id: 'c18',
        user: {
          _id: 'u7',
          fullName: 'Jason Foster',
          dp: 'https://random.imagecdn.app/215/215',
        },
        text: 'Open source contributions are so valuable. Well done!',
        likes: 15,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replies: [
          {
            _id: 'c18r1',
            user: {
              _id: 'u3',
              fullName: 'Ryan Cooper',
              dp: 'https://random.imagecdn.app/211/211',
            },
            text: 'Thanks so much! More features coming soon 👨‍💻',
            likes: 6,
            reactions: ['fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 3 * 3600000),
          },
        ],
      },
    ],
    shares: 45,
    sharesData: [
      {
        _id: 's13',
        user: {
          _id: 'u42',
          fullName: 'Shane Irving',
          dp: 'https://random.imagecdn.app/242/242',
        },
        sharedAt: new Date(Date.now() - 8 * 86400000),
      },
      {
        _id: 's14',
        user: {
          _id: 'u43',
          fullName: 'Liam Hudson',
          dp: 'https://random.imagecdn.app/243/243',
        },
        caption: 'The open-source community needs more people like this!',
        sharedAt: new Date(Date.now() - 5 * 86400000),
      },
      {
        _id: 's15',
        user: {
          _id: 'u44',
          fullName: 'Timothy Ingram',
          dp: 'https://random.imagecdn.app/244/244',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's16',
        user: {
          _id: 'u45',
          fullName: 'Noah Hudson',
          dp: 'https://random.imagecdn.app/245/245',
        },
        caption: 'Sharing this for all my dev friends 🚀',
        sharedAt: new Date(Date.now() - 6 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    user: {
      _id: 'u4',
      fullName: 'Tyler Brooks',
      username: 'tyler_a',
      dp: 'https://random.imagecdn.app/213/213',
    },
    caption:
      'Ran my first 10K this morning and I still cannot believe it. Six months ago I could barely run for five minutes without stopping. Consistency truly is everything. If you are thinking about starting — just start. Your future self will thank you. 🏃‍♂️🎉',
    image: 'https://random.imagecdn.app/1920/1020',
    likes: 874,
    comments: 61,
    commentsData: [
      {
        _id: 'c19',
        user: {
          _id: 'u6',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/214/214',
        },
        text: 'This is so inspiring! I just started running last week. 💪',
        likes: 33,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 6 * 3600000),
      },
      {
        _id: 'c20',
        user: {
          _id: 'u8',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/216/216',
        },
        text: 'Legend! Next up — half marathon? 😄',
        likes: 19,
        reactions: ['fas fa-laugh'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replies: [
          {
            _id: 'c20r1',
            user: {
              _id: 'u4',
              fullName: 'Tyler Brooks',
              dp: 'https://random.imagecdn.app/213/213',
            },
            text: 'Already signed up haha! 😅',
            likes: 11,
            reactions: ['fas fa-laugh', 'fas fa-thumbs-up'],
            createdAt: new Date(Date.now() - 3 * 3600000),
          },
        ],
      },
    ],
    shares: 29,
    sharesData: [
      {
        _id: 's17',
        user: {
          _id: 'u46',
          fullName: 'Matthew Allen',
          dp: 'https://random.imagecdn.app/246/246',
        },
        sharedAt: new Date(Date.now() - 9 * 86400000),
      },
      {
        _id: 's18',
        user: {
          _id: 'u47',
          fullName: 'Sebastian Morgan',
          dp: 'https://random.imagecdn.app/247/247',
        },
        caption: 'Motivation level 1000! Starting my running journey tomorrow.',
        sharedAt: new Date(Date.now() - 4 * 86400000),
      },
      {
        _id: 's19',
        user: {
          _id: 'u48',
          fullName: 'Spencer Andrews',
          dp: 'https://random.imagecdn.app/248/248',
        },
        sharedAt: new Date(Date.now() - 18 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 3 * 3600000),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    user: {
      _id: 'u5',
      fullName: 'Derek Morgan',
      username: 'derek_r',
      dp: 'https://random.imagecdn.app/214/214',
    },
    caption:
      'Tried making sushi at home for the first time and honestly... it went better than expected! 🍣 There is something so meditative about the process. Anyone else find cooking a great way to decompress after a long week?',
    image: 'https://random.imagecdn.app/1920/1010',
    likes: 198,
    comments: 22,
    commentsData: [
      {
        _id: 'c21',
        user: {
          _id: 'u9',
          fullName: 'Marcus Henderson',
          dp: 'https://random.imagecdn.app/217/217',
        },
        text: 'You have to share the recipe! These look amazing 😍',
        likes: 17,
        reactions: ['fas fa-heart'],
        createdAt: new Date(Date.now() - 2 * 3600000),
      },
      {
        _id: 'c22',
        user: {
          _id: 'u11',
          fullName: 'Russell Hansen',
          dp: 'https://random.imagecdn.app/219/219',
        },
        text: 'Cooking is definitely my therapy too. Looks delicious!',
        likes: 8,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 1 * 3600000),
      },
    ],
    shares: 7,
    sharesData: [
      {
        _id: 's20',
        user: {
          _id: 'u49',
          fullName: 'Ian Hudson',
          dp: 'https://random.imagecdn.app/249/249',
        },
        sharedAt: new Date(Date.now() - 2 * 86400000),
      },
      {
        _id: 's21',
        user: {
          _id: 'u50',
          fullName: 'Walter Morgan',
          dp: 'https://random.imagecdn.app/250/250',
        },
        caption: 'Cooking is my therapy too! Great post.',
        sharedAt: new Date(Date.now() - 1 * 86400000),
      },
      {
        _id: 's22',
        user: {
          _id: 'u51',
          fullName: 'Harold Ullman',
          dp: 'https://random.imagecdn.app/251/251',
        },
        sharedAt: new Date(Date.now() - 8 * 3600000),
      },
    ],
    createdAt: new Date(Date.now() - 4 * 3600000),
    updatedAt: new Date(),
  },
];

export const storiesData: IStory[] = [
  {
    _id: '1',
    image: 'https://random.imagecdn.app/200/300',
    user: {
      _id: '1',
      fullName: 'Jake Mitchell',
      dp: 'https://random.imagecdn.app/100/100',
    },
    createdAt: new Date(),
  },
  {
    _id: '2',
    image: 'https://random.imagecdn.app/200/400',
    user: {
      _id: '2',
      fullName: 'Jake',
      dp: 'https://random.imagecdn.app/200/200',
    },
    createdAt: new Date(),
  },
  {
    _id: '3',
    image: 'https://random.imagecdn.app/201/300',
    user: {
      _id: '3',
      fullName: 'Ryan Cooper',
      dp: 'https://random.imagecdn.app/201/201',
    },
    createdAt: new Date(),
  },
  {
    _id: '4',
    image: 'https://random.imagecdn.app/202/300',
    user: {
      _id: '4',
      fullName: 'Emily Carter',
      dp: 'https://random.imagecdn.app/202/202',
    },
    createdAt: new Date(),
  },
  {
    _id: '5',
    image: 'https://random.imagecdn.app/203/300',
    user: {
      _id: '5',
      fullName: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/203/203',
    },
    createdAt: new Date(),
  },
  {
    _id: '6',
    image: 'https://random.imagecdn.app/204/300',
    user: {
      _id: '6',
      fullName: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/204/204',
    },
    createdAt: new Date(),
  },
  {
    _id: '7',
    image: 'https://random.imagecdn.app/205/300',
    user: {
      _id: '7',
      fullName: 'Jason Foster',
      dp: 'https://random.imagecdn.app/205/205',
    },
    createdAt: new Date(),
  },
  {
    _id: '8',
    image: 'https://random.imagecdn.app/206/300',
    user: {
      _id: '8',
      fullName: 'Marcus Henderson',
      dp: 'https://random.imagecdn.app/206/206',
    },
    createdAt: new Date(),
  },
];

export const marketplaceListingsData: IMarketplaceListing[] = [
  {
    _id: 'ml1',
    price: 21999,
    title: 'Macbook pro 2015 256gb intel',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/300/300',
    category: 'Electronics',
    condition: 'Used - good',
    listedAgo: '2 days ago',
    description:
      '256GB SSD\nIntel Core i5 2.7GHz\n8GB RAM\n13-inch Retina display\nBattery health 89%\nMinor scratches on lid only',
    images: [
      'https://random.imagecdn.app/300/300',
      'https://random.imagecdn.app/300/302',
      'https://random.imagecdn.app/302/300',
      'https://random.imagecdn.app/298/300',
      'https://random.imagecdn.app/300/298',
    ],
    seller: {
      _id: 'sl1',
      name: 'Ryan Cooper',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'ml2',
    price: 70000,
    title: 'iPhone 15 pro.',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/301/301',
    category: 'Electronics',
    condition: 'Used - like new',
    listedAgo: '3 hours ago',
    description:
      'iPhone 15 Pro 128GB Natural Titanium\nFull box with all accessories\nScreen protector installed from day 1\nNo scratches or dents\nFace ID working perfectly\nBattery health 98%',
    images: [
      'https://random.imagecdn.app/301/301',
      'https://random.imagecdn.app/301/303',
      'https://random.imagecdn.app/303/301',
      'https://random.imagecdn.app/299/301',
      'https://random.imagecdn.app/301/299',
    ],
    seller: {
      _id: 'sl2',
      name: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'ml3',
    price: 365000,
    title: 'Honda Civic 2019',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/302/302',
    category: 'Vehicles',
    condition: 'Used - good',
    listedAgo: '5 days ago',
    description:
      '1.5L Turbo engine\nAutomatic transmission\nFull option with sunroof\n65,000 km driven\nAll papers clear\nRecent major service done',
    images: [
      'https://random.imagecdn.app/302/302',
      'https://random.imagecdn.app/302/304',
      'https://random.imagecdn.app/304/302',
      'https://random.imagecdn.app/300/302',
      'https://random.imagecdn.app/302/300',
      'https://random.imagecdn.app/306/302',
    ],
    seller: {
      _id: 'sl3',
      name: 'Jason Foster',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
  {
    _id: 'ml4',
    price: 3280000,
    title: 'Toyota Corolla 2022 fully loaded',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/303/303',
    category: 'Vehicles',
    condition: 'Used - like new',
    listedAgo: 'a week ago',
    description:
      '2.0L Hybrid engine\n12,000 km only\nAll papers in order\nSingle owner\nFull option with leather seats\nApple CarPlay & Android Auto',
    images: [
      'https://random.imagecdn.app/303/303',
      'https://random.imagecdn.app/303/305',
      'https://random.imagecdn.app/305/303',
      'https://random.imagecdn.app/301/303',
      'https://random.imagecdn.app/307/303',
    ],
    seller: {
      _id: 'sl4',
      name: 'Emily Carter',
      dp: 'https://random.imagecdn.app/212/212',
      responsive: true,
      joinedYear: 2017,
    },
  },
  {
    _id: 'ml5',
    price: 3500,
    title: 'Baseus Nomos 100W GaN Desktop Charging Station Multi Port',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/304/304',
    category: 'Electronics',
    condition: 'Brand new',
    listedAgo: 'a day ago',
    description:
      '100W GaN Technology\n6 ports total (2 USB-C + 4 USB-A)\nSupports PD 3.0 & QC 4.0\nDesktop stand design\nOriginal box included\nPrice is fixed',
    images: [
      'https://random.imagecdn.app/304/304',
      'https://random.imagecdn.app/304/306',
      'https://random.imagecdn.app/306/304',
      'https://random.imagecdn.app/302/304',
    ],
    seller: {
      _id: 'sl1',
      name: 'Ryan Cooper',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'ml6',
    price: 2000,
    title: 'Study table',
    location: 'Chandpur, Bangladesh',
    image: 'https://random.imagecdn.app/305/305',
    category: 'Home Goods',
    condition: 'Used - fair',
    listedAgo: '4 days ago',
    description:
      'Wooden study table with drawer\n120cm x 60cm size\nSlightly scratched on top surface\nAll screws intact\nMust pick up from Chandpur\nBargain accepted',
    images: [
      'https://random.imagecdn.app/305/305',
      'https://random.imagecdn.app/305/307',
      'https://random.imagecdn.app/307/305',
      'https://random.imagecdn.app/303/305',
    ],
    seller: {
      _id: 'sl5',
      name: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'ml7',
    price: 45000,
    title: 'Samsung S22 Ultra 12/256',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/306/306',
    category: 'Electronics',
    condition: 'Used - like new',
    listedAgo: '6 hours ago',
    description:
      'Samsung Galaxy S22 Ultra\n12GB RAM / 256GB storage\nBuilt-in S Pen\nPhantom Black color\nScreen protector from day 1\nBattery health excellent\nAll accessories included',
    images: [
      'https://random.imagecdn.app/306/306',
      'https://random.imagecdn.app/306/308',
      'https://random.imagecdn.app/308/306',
      'https://random.imagecdn.app/304/306',
      'https://random.imagecdn.app/306/304',
    ],
    seller: {
      _id: 'sl2',
      name: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'ml8',
    price: 1250000,
    title: 'BMW 520i 2018 executive edition',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/307/307',
    category: 'Vehicles',
    condition: 'Used - good',
    listedAgo: '2 weeks ago',
    description:
      '2.0L TwinPower Turbo\n50,000 km driven\nExecutive package with HUD\nLane departure warning\nHeated front seats\nAll original BMW parts\nPapers fully clear',
    images: [
      'https://random.imagecdn.app/307/307',
      'https://random.imagecdn.app/307/309',
      'https://random.imagecdn.app/309/307',
      'https://random.imagecdn.app/305/307',
      'https://random.imagecdn.app/311/307',
      'https://random.imagecdn.app/307/305',
    ],
    seller: {
      _id: 'sl6',
      name: 'Michael Campbell',
      dp: 'https://random.imagecdn.app/216/216',
      responsive: false,
      joinedYear: 2016,
    },
  },
  {
    _id: 'ml9',
    price: 12500,
    title: 'Apple iPod nano (7th Generation)',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/308/308',
    category: 'Electronics',
    condition: 'Used - good',
    listedAgo: '3 days ago',
    description:
      'iPod Nano 7th Gen 16GB\nSpace Gray color\nWorks perfectly\nBattery holds charge well\nComes with original cable\nLight scratches on back only',
    images: [
      'https://random.imagecdn.app/308/308',
      'https://random.imagecdn.app/308/310',
      'https://random.imagecdn.app/310/308',
      'https://random.imagecdn.app/306/308',
    ],
    seller: {
      _id: 'sl5',
      name: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'ml10',
    price: 65000,
    title: 'Full PC Setup for sale',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/309/309',
    category: 'Electronics',
    condition: 'Used - good',
    listedAgo: '5 hours ago',
    description:
      'Intel i5 10th Gen\n16GB DDR4 RAM\n512GB SSD + 1TB HDD\nNvidia GTX 1660 Super 6GB\n24" FHD 144Hz Monitor\nMechanical keyboard + Gaming mouse\nUPS included',
    images: [
      'https://random.imagecdn.app/309/309',
      'https://random.imagecdn.app/309/311',
      'https://random.imagecdn.app/311/309',
      'https://random.imagecdn.app/307/309',
      'https://random.imagecdn.app/313/309',
    ],
    seller: {
      _id: 'sl3',
      name: 'Jason Foster',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
  {
    _id: 'ml11',
    price: 6350000,
    title: 'Mercedes-Benz C300 2021',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/310/310',
    category: 'Vehicles',
    condition: 'Used - like new',
    listedAgo: '10 days ago',
    description:
      '2.0L Turbo 258hp\n18,000 km driven\nAMG Line package\nBurmester sound system\nDigital cockpit\nAll tax paid and papers clear\nSingle owner, company car',
    images: [
      'https://random.imagecdn.app/310/310',
      'https://random.imagecdn.app/310/312',
      'https://random.imagecdn.app/312/310',
      'https://random.imagecdn.app/308/310',
      'https://random.imagecdn.app/314/310',
      'https://random.imagecdn.app/310/308',
    ],
    seller: {
      _id: 'sl4',
      name: 'Emily Carter',
      dp: 'https://random.imagecdn.app/212/212',
      responsive: true,
      joinedYear: 2017,
    },
  },
  {
    _id: 'ml12',
    price: 28500,
    title: 'Redmi Note 13 Pro 5G 256GB',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/311/311',
    category: 'Electronics',
    condition: 'Brand new',
    listedAgo: '12 hours ago',
    description:
      'Redmi Note 13 Pro 5G\n8GB RAM / 256GB storage\nMidnight Black\nSealed box, never opened\nOfficial warranty card included\nPrice slightly negotiable',
    images: [
      'https://random.imagecdn.app/311/311',
      'https://random.imagecdn.app/311/313',
      'https://random.imagecdn.app/313/311',
      'https://random.imagecdn.app/309/311',
    ],
    seller: {
      _id: 'sl1',
      name: 'Ryan Cooper',
      dp: 'https://random.imagecdn.app/211/211',
      responsive: true,
      joinedYear: 2019,
    },
  },
  {
    _id: 'ml13',
    price: 0,
    isFree: true,
    title: 'Credit Card',
    location: 'Chandpur, Bangladesh',
    image: 'https://random.imagecdn.app/312/312',
    category: 'Free Stuff',
    listedAgo: 'just now',
    description:
      'Free UCB credit card\nApply now and get approved quickly\nNo annual fee for first year\nUp to BDT 3 lakh credit limit\nContact for details',
    images: [
      'https://random.imagecdn.app/312/312',
      'https://random.imagecdn.app/312/314',
      'https://random.imagecdn.app/314/312',
    ],
    seller: {
      _id: 'sl5',
      name: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/214/214',
      responsive: true,
      joinedYear: 2021,
    },
  },
  {
    _id: 'ml14',
    price: 57500,
    title: 'iPhone 16 pro max 256 GB',
    location: 'Narayanganj, Bangladesh',
    image: 'https://random.imagecdn.app/313/313',
    category: 'Electronics',
    condition: 'Used - like new',
    listedAgo: 'a day ago',
    description:
      'Baypass\n256 GB\nDisplay Change Original ta lagano Gx\nCondition Fresh\nSecurity Nid\nAnd parts a sudhu exchange korar ager phone nibo',
    images: [
      'https://random.imagecdn.app/313/313',
      'https://random.imagecdn.app/313/315',
      'https://random.imagecdn.app/315/313',
      'https://random.imagecdn.app/311/313',
      'https://random.imagecdn.app/317/313',
      'https://random.imagecdn.app/313/311',
    ],
    seller: {
      _id: 'sl7',
      name: 'Hunter Shelton',
      dp: 'https://random.imagecdn.app/270/270',
      responsive: true,
      joinedYear: 2022,
    },
  },
  {
    _id: 'ml15',
    price: 60000,
    title: 'iPhone 15 pro max',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/314/314',
    category: 'Electronics',
    condition: 'Used - like new',
    listedAgo: '2 days ago',
    description:
      'iPhone 15 Pro Max 256GB\nBlack Titanium\nBattery health 97%\nNo scratches, always in case\nFull box with all accessories\nNegotiable price',
    images: [
      'https://random.imagecdn.app/314/314',
      'https://random.imagecdn.app/314/316',
      'https://random.imagecdn.app/316/314',
      'https://random.imagecdn.app/312/314',
      'https://random.imagecdn.app/318/314',
    ],
    seller: {
      _id: 'sl6',
      name: 'Michael Campbell',
      dp: 'https://random.imagecdn.app/216/216',
      responsive: false,
      joinedYear: 2016,
    },
  },
  {
    _id: 'ml16',
    price: 23900,
    title: 'iPhone 13 pro 256gb (1 cloud lock)',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/315/315',
    category: 'Electronics',
    condition: 'Used - fair',
    listedAgo: '4 days ago',
    description:
      'iPhone 13 Pro 256GB\nSierra Blue color\n1 iCloud lock — previous owner account\nPrice reflects the issue\nAll hardware fully working\nBattery health 84%\nFor tech savvy buyers only',
    images: [
      'https://random.imagecdn.app/315/315',
      'https://random.imagecdn.app/315/317',
      'https://random.imagecdn.app/317/315',
      'https://random.imagecdn.app/313/315',
    ],
    seller: {
      _id: 'sl2',
      name: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/213/213',
      responsive: true,
      joinedYear: 2020,
    },
  },
  {
    _id: 'ml17',
    price: 64000,
    title: 'iPhone 16 pro bypass',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/316/316',
    category: 'Electronics',
    condition: 'Used - good',
    listedAgo: '3 days ago',
    description:
      'iPhone 16 Pro 128GB\nBypass activation — works normally\nAll features functional including Face ID\nScreen replaced (original quality)\nBattery 91%\nComes with charger only',
    images: [
      'https://random.imagecdn.app/316/316',
      'https://random.imagecdn.app/316/318',
      'https://random.imagecdn.app/318/316',
      'https://random.imagecdn.app/314/316',
      'https://random.imagecdn.app/316/314',
    ],
    seller: {
      _id: 'sl7',
      name: 'Hunter Shelton',
      dp: 'https://random.imagecdn.app/270/270',
      responsive: true,
      joinedYear: 2022,
    },
  },
  {
    _id: 'ml18',
    price: 18000,
    title: 'Microsoft Surface Pro 4 everything all',
    location: 'Dhaka, Bangladesh',
    image: 'https://random.imagecdn.app/317/317',
    category: 'Electronics',
    condition: 'Used - good',
    listedAgo: '6 days ago',
    description:
      'Microsoft Surface Pro 4\nIntel Core i5 6th Gen\n8GB RAM / 256GB SSD\nType Cover keyboard included\nSurface Pen included\nMinor scuff on kickstand\nAll ports working',
    images: [
      'https://random.imagecdn.app/317/317',
      'https://random.imagecdn.app/317/319',
      'https://random.imagecdn.app/319/317',
      'https://random.imagecdn.app/315/317',
      'https://random.imagecdn.app/317/315',
    ],
    seller: {
      _id: 'sl3',
      name: 'Jason Foster',
      dp: 'https://random.imagecdn.app/215/215',
      responsive: false,
      joinedYear: 2018,
    },
  },
];

const GTV = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample';

export const reelsData: IReel[] = [
  {
    _id: 'rl1',
    user: {
      _id: 'u60',
      fullName: 'Accessories',
      username: 'accessories_shop',
      dp: 'https://random.imagecdn.app/260/260',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerBlazes.mp4`,
    poster: 'https://random.imagecdn.app/400/711',
    caption:
      'One drop and your teeth are spotless clean in seconds! 😍 Must try this at home.',
    audio: 'Accessories · Original audio',
    likes: 116,
    comments: 129,
    shares: 20,
    createdAt: new Date(Date.now() - 9 * 3600000),
  },
  {
    _id: 'rl2',
    user: {
      _id: 'u61',
      fullName: 'Ryan Dev',
      username: 'ryan_dev',
      dp: 'https://random.imagecdn.app/261/261',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/ForBiggerEscapes.mp4`,
    poster: 'https://random.imagecdn.app/401/711',
    caption:
      'Built a full-stack app in 60 minutes using React + Node. Here is how 🚀 #coding #webdev',
    audio: 'Lofi Study Beats · Chill Mix',
    likes: 2400,
    comments: 318,
    shares: 145,
    createdAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    _id: 'rl3',
    user: {
      _id: 'u62',
      fullName: 'Jason Travels',
      username: 'jason_travels',
      dp: 'https://random.imagecdn.app/262/262',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerFun.mp4`,
    poster: 'https://random.imagecdn.app/402/711',
    caption:
      "Cox's Bazar at golden hour hits different 🌅 The most beautiful beach I've ever visited. Pack your bags!",
    audio: 'Jason Travels · Original audio',
    likes: 8700,
    comments: 542,
    shares: 892,
    createdAt: new Date(Date.now() - 14 * 3600000),
  },
  {
    _id: 'rl4',
    user: {
      _id: 'u63',
      fullName: 'Chef Emily',
      username: 'chef_emily',
      dp: 'https://random.imagecdn.app/263/263',
      isVerified: false,
      isFollowing: false,
    },
    videoUrl: `${GTV}/ForBiggerJoyrides.mp4`,
    poster: 'https://random.imagecdn.app/403/711',
    caption:
      '5-minute homemade sushi that actually looks amazing 🍣 Recipe in the comments!',
    audio: 'Cooking Vibes · Chill House',
    likes: 3200,
    comments: 411,
    shares: 267,
    createdAt: new Date(Date.now() - 22 * 3600000),
  },
  {
    _id: 'rl5',
    user: {
      _id: 'u64',
      fullName: 'Tyler Fit',
      username: 'tyler_fit',
      dp: 'https://random.imagecdn.app/264/264',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/ForBiggerMeltdowns.mp4`,
    poster: 'https://random.imagecdn.app/404/711',
    caption:
      "10K in 45 minutes. Six months ago I couldn't run for 5 minutes. Consistency is everything 💪",
    audio: 'Workout Motivation · DJ Mix',
    likes: 12400,
    comments: 730,
    shares: 1100,
    createdAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    _id: 'rl6',
    user: {
      _id: 'u65',
      fullName: 'Michael Speaks',
      username: 'michael_speaks',
      dp: 'https://random.imagecdn.app/265/265',
      isVerified: true,
      isFollowing: false,
    },
    videoUrl: `${GTV}/BigBuckBunny.mp4`,
    poster: 'https://random.imagecdn.app/405/711',
    caption:
      'Stop waiting for the perfect moment. Start now, perfect it later. 🔥 #motivation #mindset',
    audio: 'Michael Speaks · Original audio',
    likes: 45000,
    comments: 2100,
    shares: 6800,
    createdAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    _id: 'rl7',
    user: {
      _id: 'u66',
      fullName: 'Tech With Frank',
      username: 'tech_frank',
      dp: 'https://random.imagecdn.app/266/266',
      isVerified: false,
      isFollowing: false,
    },
    videoUrl: `${GTV}/TearsOfSteel.mp4`,
    poster: 'https://random.imagecdn.app/406/711',
    caption:
      'Unboxing the new flagship phone — is it worth 100K BDT? My honest review after 2 weeks 📱',
    audio: 'Tech With Frank · Original audio',
    likes: 5600,
    comments: 890,
    shares: 340,
    createdAt: new Date(Date.now() - 4 * 86400000),
  },
  {
    _id: 'rl8',
    user: {
      _id: 'u67',
      fullName: 'Derek Lifestyle',
      username: 'derek_life',
      dp: 'https://random.imagecdn.app/267/267',
      isVerified: false,
      isFollowing: true,
    },
    videoUrl: `${GTV}/WeAreGoingOnBullrun.mp4`,
    poster: 'https://random.imagecdn.app/407/711',
    caption:
      'Morning routine that changed my life ☀️ Wake up at 5AM and watch what happens in 30 days.',
    audio: 'Morning Calm · Meditation Mix',
    likes: 19200,
    comments: 1430,
    shares: 3200,
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
];

export const topPicksData: IGame[] = [
  {
    _id: 'g1',
    title: 'Ludo Club',
    image: 'https://random.imagecdn.app/320/321',
    category: 'Board',
    players: [
      { _id: 'gp1', dp: 'https://random.imagecdn.app/50/51' },
      { _id: 'gp2', dp: 'https://random.imagecdn.app/51/50' },
      { _id: 'gp3', dp: 'https://random.imagecdn.app/52/50' },
    ],
  },
  {
    _id: 'g2',
    title: 'UNO',
    image: 'https://random.imagecdn.app/321/320',
    category: 'Card',
    players: [
      { _id: 'gp4', dp: 'https://random.imagecdn.app/53/50' },
      { _id: 'gp5', dp: 'https://random.imagecdn.app/54/50' },
    ],
  },
  {
    _id: 'g3',
    title: '8 Ball Pool',
    image: 'https://random.imagecdn.app/322/320',
    category: 'Sport',
    players: [
      { _id: 'gp6', dp: 'https://random.imagecdn.app/55/50' },
      { _id: 'gp7', dp: 'https://random.imagecdn.app/56/50' },
      { _id: 'gp8', dp: 'https://random.imagecdn.app/57/50' },
    ],
  },
  {
    _id: 'g4',
    title: 'Ludo King - Instant',
    image: 'https://random.imagecdn.app/323/320',
    category: 'Board',
  },
  {
    _id: 'g5',
    title: 'Family Farm Journey',
    image: 'https://random.imagecdn.app/324/320',
    category: 'Simulation',
  },
  {
    _id: 'g6',
    title: 'Chess Royale',
    image: 'https://random.imagecdn.app/325/320',
    category: 'Sport',
  },
  {
    _id: 'g7',
    title: 'Carrom',
    image: 'https://random.imagecdn.app/326/320',
    category: 'Board',
    players: [
      { _id: 'gp9', dp: 'https://random.imagecdn.app/58/50' },
      { _id: 'gp10', dp: 'https://random.imagecdn.app/59/50' },
    ],
  },
  {
    _id: 'g8',
    title: 'MergeVille',
    image: 'https://random.imagecdn.app/327/320',
    category: 'Builder',
  },
  {
    _id: 'g9',
    title: 'Ludo World',
    image: 'https://random.imagecdn.app/328/320',
    category: 'Board',
    players: [
      { _id: 'gp11', dp: 'https://random.imagecdn.app/60/50' },
      { _id: 'gp12', dp: 'https://random.imagecdn.app/61/50' },
      { _id: 'gp13', dp: 'https://random.imagecdn.app/62/50' },
    ],
  },
  {
    _id: 'g10',
    title: 'WormsZone.io - Slither Snake',
    image: 'https://random.imagecdn.app/329/320',
    category: 'Arcade',
  },
  {
    _id: 'g11',
    title: 'Carrom Gold',
    image: 'https://random.imagecdn.app/330/320',
    category: 'Board',
    players: [
      { _id: 'gp14', dp: 'https://random.imagecdn.app/63/50' },
      { _id: 'gp15', dp: 'https://random.imagecdn.app/64/50' },
    ],
  },
  {
    _id: 'g12',
    title: 'Merge Haven',
    image: 'https://random.imagecdn.app/331/320',
    category: 'Merge',
  },
  {
    _id: 'g13',
    title: 'Chess',
    image: 'https://random.imagecdn.app/332/320',
    category: 'Board',
  },
  {
    _id: 'g14',
    title: 'TopWar',
    image: 'https://random.imagecdn.app/333/320',
    category: 'Battle',
  },
  {
    _id: 'g15',
    title: 'Mergest Kingdom',
    image: 'https://random.imagecdn.app/334/320',
    category: 'Builder',
  },
  {
    _id: 'g16',
    title: 'Soccer Championship',
    image: 'https://random.imagecdn.app/335/320',
    category: 'Sport',
  },
];

export const gameEventsData: IGameEvent[] = [
  {
    _id: 'ge1',
    gameTitle: 'Slots Heart Casino',
    gameIcon: 'https://random.imagecdn.app/48/48',
    eventImage: 'https://random.imagecdn.app/400/560',
    title: 'New Slot: World Champions',
    description:
      'Celebrate 2026 football with a new slot game featuring your favorite teams!',
    endsInDays: 11,
  },
  {
    _id: 'ge2',
    gameTitle: 'Fairyland Merge & Magic',
    gameIcon: 'https://random.imagecdn.app/49/48',
    eventImage: 'https://random.imagecdn.app/401/560',
    title: 'Fairy Graduation',
    description:
      'Celebrate a magical graduation day. Collect rare fairy items and unlock rewards.',
    endsInDays: 12,
  },
  {
    _id: 'ge3',
    gameTitle: 'Mergest Kingdom',
    gameIcon: 'https://random.imagecdn.app/50/48',
    eventImage: 'https://random.imagecdn.app/402/560',
    title: 'Enchanted Prom',
    description:
      'Explore a magical academy celebration. Merge items and earn exclusive prizes.',
    endsInDays: 12,
  },
  {
    _id: 'ge4',
    gameTitle: 'Arrow Slide Puzzle',
    gameIcon: 'https://random.imagecdn.app/51/48',
    eventImage: 'https://random.imagecdn.app/403/560',
    title: 'New Worlds to Explore',
    description:
      'Discover beautiful new locations with challenging arrow puzzles to solve.',
    endsInDays: 12,
  },
  {
    _id: 'ge5',
    gameTitle: 'Fantasy Slots',
    gameIcon: 'https://random.imagecdn.app/52/48',
    eventImage: 'https://random.imagecdn.app/404/560',
    title: 'New Game: Double Ingots',
    description:
      'New slot machine game is available now! Spin for massive gold rewards.',
    endsInDays: 8,
  },
  {
    _id: 'ge6',
    gameTitle: 'Winning Slots',
    gameIcon: 'https://random.imagecdn.app/53/48',
    eventImage: 'https://random.imagecdn.app/405/560',
    title: 'Gem Miner Launch',
    description:
      'The slot machine is unlocked. Spin now and mine your way to riches!',
    endsInDays: 7,
  },
  {
    _id: 'ge7',
    gameTitle: 'Ludo Club',
    gameIcon: 'https://random.imagecdn.app/54/48',
    eventImage: 'https://random.imagecdn.app/406/560',
    title: 'Grand Championship',
    description:
      'Compete in the ultimate Ludo tournament. Win exclusive board themes and trophies.',
    endsInDays: 15,
  },
];

export const mostPlayedData: IGame[] = [
  {
    _id: 'mp1',
    title: '8 Ball Pool',
    image: 'https://random.imagecdn.app/340/341',
    category: 'Sport',
  },
  {
    _id: 'mp2',
    title: 'Basketball Stars',
    image: 'https://random.imagecdn.app/341/340',
    category: 'Sport',
  },
  {
    _id: 'mp3',
    title: 'Word Blitz',
    image: 'https://random.imagecdn.app/342/340',
    category: 'Word',
  },
  {
    _id: 'mp4',
    title: 'Mini Golf FRVR',
    image: 'https://random.imagecdn.app/343/340',
    category: 'Sport',
  },
  {
    _id: 'mp5',
    title: 'Coin Match',
    image: 'https://random.imagecdn.app/344/340',
    category: 'Match',
  },
  {
    _id: 'mp6',
    title: 'Chess Quest',
    image: 'https://random.imagecdn.app/345/340',
    category: 'Strategy',
  },
  {
    _id: 'mp7',
    title: 'Solitaire',
    image: 'https://random.imagecdn.app/346/340',
    category: 'Card',
  },
  {
    _id: 'mp8',
    title: 'Bingo Blitz',
    image: 'https://random.imagecdn.app/347/340',
    category: 'Casino',
  },
];

export const groupsData: IGroup[] = [
  {
    _id: 'grp1',
    name: 'SWE 22 Dynamic & Democratic C Section',
    image: 'https://random.imagecdn.app/360/360',
    lastActive: 'Last active 5 years ago',
    isPinned: true,
  },
  {
    _id: 'grp2',
    name: 'Games World গেমস ওয়ার্ল্ড (GWF)',
    image: 'https://random.imagecdn.app/361/361',
    lastActive: 'Last active 44 minutes ago',
  },
  {
    _id: 'grp3',
    name: 'Dev for Hire (CSE/EEE/IT Jobs in bangladesh)',
    image: 'https://random.imagecdn.app/362/362',
    lastActive: 'Last active 58 minutes ago',
  },
  {
    _id: 'grp4',
    name: 'Malaysia Software Developer Jobs Community',
    image: 'https://random.imagecdn.app/363/363',
    lastActive: 'Last active 6 hours ago',
  },
  {
    _id: 'grp5',
    name: 'NodeJS Bangladesh',
    image: 'https://random.imagecdn.app/364/364',
    lastActive: 'Last active 8 hours ago',
  },
  {
    _id: 'grp6',
    name: 'Remote IT Jobs',
    image: 'https://random.imagecdn.app/365/365',
    lastActive: 'Last active a day ago',
  },
  {
    _id: 'grp7',
    name: 'Engaze Community & Support',
    image: 'https://random.imagecdn.app/366/366',
    lastActive: 'Last active 19 weeks ago',
  },
  {
    _id: 'grp8',
    name: 'Find Web Developer ( Bangladesh )',
    image: 'https://random.imagecdn.app/367/367',
    lastActive: 'Last active 2 hours ago',
  },
  {
    _id: 'grp9',
    name: 'KBKh | কি...বিজ্ঞান খুঁজছেন?',
    image: 'https://random.imagecdn.app/368/368',
    lastActive: 'Last active 46 minutes ago',
  },
  {
    _id: 'grp10',
    name: 'Vacancy Announcement BD (Freshers & Experienced) by thecvguy.net',
    image: 'https://random.imagecdn.app/369/369',
    lastActive: 'Last active a week ago',
  },
];

export const groupPostsData: IGroupPost[] = [
  {
    _id: 'gp1',
    group: {
      _id: 'grp-claude',
      name: 'Claude Ai Community',
      image: 'https://random.imagecdn.app/370/370',
      isPublic: true,
    },
    user: {
      _id: 'gu1',
      fullName: 'Andy Montesino',
      dp: 'https://random.imagecdn.app/371/371',
      badge: 'All-star contributor',
    },
    content:
      'What do you have your Claude do everyday that you always wished you could automate?',
    createdAt: new Date(Date.now() - 4 * 86400000),
    likes: 92,
    likeReactions: ['fas fa-thumbs-up'],
    commentsCount: 166,
    sharesCount: 5,
    comments: [
      {
        _id: 'gc1',
        user: {
          _id: 'gu2',
          fullName: 'OD Mansfield',
          dp: 'https://random.imagecdn.app/372/372',
        },
        text: 'Every Friday Claude asks me what I want to eat for the week. I answer, it shops for me, adds it all to cart, I verify, then it emails me the recipes and prep sheet. Video link below. Enjoy!',
        likes: 80,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart', 'fas fa-surprise'],
        createdAt: new Date(Date.now() - 3 * 86400000),
        replyCount: 29,
      },
      {
        _id: 'gc2',
        user: {
          _id: 'gu3',
          fullName: 'DeterminedHedgehog000',
          dp: 'https://random.imagecdn.app/373/373',
        },
        text: 'I put 5 years of bank PDF statements to Claude, had it put everything in spreadsheet. Now I can ask it anything. Find any expense car related. Find patents to... show me expenditure summary for 2025',
        likes: 41,
        reactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
        createdAt: new Date(Date.now() - 3 * 86400000),
        replyCount: 0,
      },
    ],
  },
  {
    _id: 'gp2',
    group: {
      _id: 'grp-claude',
      name: 'Claude Ai Community',
      image: 'https://random.imagecdn.app/370/370',
      isPublic: true,
    },
    user: {
      _id: 'gu4',
      fullName: 'Alex Bennett',
      dp: 'https://random.imagecdn.app/374/374',
      badge: 'Top contributor',
    },
    content:
      'I am look for a Co-Founder specialised in Sales, Marketing, GTM and Growth Strategy.\n\nBased in The US.\n\nMinimum 8 years of experience.',
    createdAt: new Date(Date.now() - 23 * 3600000),
    likes: 22,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-laugh'],
    commentsCount: 31,
    sharesCount: 0,
    comments: [
      {
        _id: 'gc3',
        user: {
          _id: 'gu5',
          fullName: 'Jacob Higgins',
          dp: 'https://random.imagecdn.app/375/375',
          isVerified: true,
          isFollowing: true,
        },
        text: 'Hope you find them. I get this offer 5+ times a day. Very few people were an actual operator before AI.',
        likes: 3,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 22 * 3600000),
        replyCount: 1,
      },
      {
        _id: 'gc4',
        user: {
          _id: 'gu6',
          fullName: 'Brad Brown',
          dp: 'https://random.imagecdn.app/376/376',
          isVerified: true,
        },
        text: 'Hahahaha why not advertise it in Pakistan? 😄',
        likes: 0,
        reactions: [],
        createdAt: new Date(Date.now() - 21 * 3600000),
        replyCount: 0,
      },
    ],
  },
  {
    _id: 'gp3',
    group: {
      _id: 'grp-nodejs',
      name: 'NodeJS Bangladesh',
      image: 'https://random.imagecdn.app/364/364',
      isPublic: false,
    },
    user: {
      _id: 'gu7',
      fullName: 'Ryan Dev',
      dp: 'https://random.imagecdn.app/377/377',
      badge: 'Admin',
    },
    content:
      'Just released a new open-source Node.js package for handling JWT authentication with refresh token rotation. Would love some feedback from the community! 🚀\n\n⭐ GitHub link in the comments.',
    createdAt: new Date(Date.now() - 5 * 3600000),
    likes: 148,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-heart'],
    commentsCount: 42,
    sharesCount: 17,
    comments: [
      {
        _id: 'gc5',
        user: {
          _id: 'gu8',
          fullName: 'Tyler Brooks',
          dp: 'https://random.imagecdn.app/378/378',
        },
        text: 'This is exactly what I needed! Going to integrate this into my current project.',
        likes: 12,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 4 * 3600000),
        replyCount: 2,
      },
      {
        _id: 'gc6',
        user: {
          _id: 'gu9',
          fullName: 'Emily Carter',
          dp: 'https://random.imagecdn.app/379/379',
        },
        text: 'Does this support multiple device sessions? Would be great for mobile + web.',
        likes: 7,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 3 * 3600000),
        replyCount: 1,
      },
    ],
  },
  {
    _id: 'gp4',
    group: {
      _id: 'grp-devhire',
      name: 'Dev for Hire (CSE/EEE/IT Jobs in bangladesh)',
      image: 'https://random.imagecdn.app/362/362',
      isPublic: true,
    },
    user: {
      _id: 'gu10',
      fullName: 'Jason Foster',
      dp: 'https://random.imagecdn.app/380/380',
    },
    content:
      '🔥 Hiring Alert!\n\nPosition: Senior React Developer\nCompany: TechCorp BD (Remote)\nSalary: 80,000 - 120,000 BDT\nExperience: 3+ years\n\nRequired: React, TypeScript, Node.js, REST APIs\n\nDM or comment your CV link below 👇',
    createdAt: new Date(Date.now() - 2 * 3600000),
    likes: 67,
    likeReactions: ['fas fa-thumbs-up', 'fas fa-heart'],
    commentsCount: 89,
    sharesCount: 34,
    comments: [
      {
        _id: 'gc7',
        user: {
          _id: 'gu11',
          fullName: 'Derek Morgan',
          dp: 'https://random.imagecdn.app/381/381',
        },
        text: 'Is this open for freshers with strong portfolio?',
        likes: 4,
        reactions: ['fas fa-thumbs-up'],
        createdAt: new Date(Date.now() - 1 * 3600000),
        replyCount: 1,
      },
      {
        _id: 'gc8',
        user: {
          _id: 'gu12',
          fullName: 'Michael Campbell',
          dp: 'https://random.imagecdn.app/382/382',
        },
        text: 'Sent my CV. 4 years experience with React + TypeScript. Fingers crossed! 🤞',
        likes: 9,
        reactions: ['fas fa-thumbs-up', 'fas fa-heart'],
        createdAt: new Date(Date.now() - 45 * 60000),
        replyCount: 0,
      },
    ],
  },
];

export const chatsData: IChat[] = [
  {
    _id: 'ch1',
    user: {
      _id: 'cu1',
      fullName: 'Ryan Cooper',
      dp: 'https://random.imagecdn.app/211/211',
      isOnline: true,
    },
    lastMessage: 'Where should we start the project from?',
    time: '2m',
    isUnread: true,
  },
  {
    _id: 'ch2',
    user: {
      _id: 'cu2',
      fullName: 'Emily Carter',
      dp: 'https://random.imagecdn.app/212/212',
      isOnline: true,
    },
    lastMessage: 'You: Haha okay sure, lets do it!',
    time: '45m',
    rightDp: 'https://random.imagecdn.app/500/200',
  },
  {
    _id: 'ch3',
    user: {
      _id: 'cu3',
      fullName: 'Tyler Brooks',
      dp: 'https://random.imagecdn.app/213/213',
    },
    lastMessage: 'Tyler sent a voice message.',
    time: '1h',
    isUnread: true,
  },
  {
    _id: 'ch4',
    user: {
      _id: 'cu4',
      fullName: 'Derek Morgan',
      dp: 'https://random.imagecdn.app/214/214',
      isOnline: true,
    },
    lastMessage: 'You: Thanks for the help, really appreciate it!',
    time: '3h',
  },
  {
    _id: 'ch5',
    user: {
      _id: 'cu5',
      fullName: 'Dev Squad 🚀',
      dp: 'https://random.imagecdn.app/380/380',
      isGroup: true,
    },
    lastMessage: 'Ryan: Review is done, go ahead and merge the PR.',
    time: '5h',
    isMuted: true,
  },
  {
    _id: 'ch6',
    user: {
      _id: 'cu6',
      fullName: 'Jason Foster',
      dp: 'https://random.imagecdn.app/215/215',
      isOnline: true,
    },
    lastMessage: 'Jason sent an attachment.',
    time: '7h',
    hasReply: true,
  },
  {
    _id: 'ch7',
    user: {
      _id: 'cu7',
      fullName: 'Michael Campbell',
      dp: 'https://random.imagecdn.app/216/216',
    },
    lastMessage: 'You: Will call you after lunch.',
    time: '12h',
  },
  {
    _id: 'ch8',
    user: {
      _id: 'cu8',
      fullName: 'SWE Batch 22 🎓',
      dp: 'https://random.imagecdn.app/360/360',
      isGroup: true,
      isOnline: true,
    },
    lastMessage: 'Marcus: Does anyone know when the exam results come out?',
    time: '1d',
    isMuted: true,
  },
  {
    _id: 'ch9',
    user: {
      _id: 'cu9',
      fullName: 'Russell Hansen',
      dp: 'https://random.imagecdn.app/219/219',
      isOnline: true,
    },
    lastMessage: 'Are we meeting up tomorrow?',
    time: '2d',
    hasReply: true,
  },
  {
    _id: 'ch10',
    user: {
      _id: 'cu10',
      fullName: 'Marcus Henderson',
      dp: 'https://random.imagecdn.app/217/217',
    },
    lastMessage: 'You: Got it, sending the files now.',
    time: '3d',
    hasFollowUp: true,
  },
  {
    _id: 'ch11',
    user: {
      _id: 'cu11',
      fullName: 'Nathan Hayes',
      dp: 'https://random.imagecdn.app/220/220',
    },
    lastMessage: 'Nathan sent a photo.',
    time: '4d',
  },
  {
    _id: 'ch12',
    user: {
      _id: 'cu12',
      fullName: 'Meta AI',
      dp: '',
      isMetaAI: true,
    },
    lastMessage: "Ask me anything — I'm here to help! ✨",
    time: '1w',
  },
];
